[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /home/vsss/repos/vsss24-ws/build/univector/.pytest_cache
rootdir: /home/vsss/repos/vsss24-ws/src/univector
plugins: ament-flake8-0.12.9, launch-testing-1.0.4, ament-copyright-0.12.9, ament-xmllint-0.12.9, ament-pep257-0.12.9, ament-lint-0.12.9, launch-testing-ros-0.19.6, rerunfailures-12.0, colcon-core-0.12.1, cov-4.1.0, repeat-0.9.1
[1mcollecting ... [0m[1m
collected 1 item                                                               [0m

test/test_univector.py [31mF[0m[31m                                                 [100%][0m

=================================== FAILURES ===================================
[31m[1m__________________________________ test_norm ___________________________________[0m
[1m[31mtest/test_univector.py[0m:11: in test_norm
    [94massert[39;49;00m resultado_esperado == resultado_norma
[1m[31mE   assert 5 == 5.656854249492381[0m
-- generated xml file: /home/vsss/repos/vsss24-ws/build/univector/pytest.xml ---
=========================== short test summary info ============================
FAILED test/test_univector.py::test_norm - assert 5 == 5.656854249492381
[31m============================== [31m[1m1 failed[0m[31m in 0.17s[0m[31m ===============================[0m
